[project]
name = "foundational-model-for-energy-security"
version = "0.1.0"
description = ""
authors = [
    {name = "jorel", email = "jorel.abrantes@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "pandas>=2.3.3,<3.0.0",
    "pyshark (>=0.6,<0.7)",
    "scapy (>=2.7.0,<3.0.0)",
    "ipykernel (>=7.1.0,<8.0.0)",
    "nest-asyncio (>=1.6.0,<2.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "tensorflow (>=2.20.0,<3.0.0)",
    "torch (>=2.10.0,<3.0.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"